Repository erwindouna/python-tado, pull requests merged in 2024-10, with the labels that each got.

#85 Add childLock feature
  poetry.lock
  pyproject.toml
  src/tadoasync/tadoasync.py
  tests/test_tado.py
Labels: new-feature

#86 Creating new version
  poetry.lock
  pyproject.toml
  src/tadoasync/tadoasync.py
Labels: enhancement

#81 hot water zone compatibility bug fix
  src/tadoasync/models.py
Labels: enhancement, refactor

#88 Fix linter & documentation
  README.md
  poetry.lock
  pyproject.toml
  src/tadoasync/models.py
Labels: documentation, refactor

#89 Refactor check status & minor adjustments
  README.md
  src/tadoasync/tadoasync.py
  tests/test_tado.py
Labels: refactor
